version: '7.10'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - esnet

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src  # Mount your local source code directory into the container
    environment:
      NODE_ENV: development  # Set NODE_ENV to development for development purposes
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

  prisma:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://prisma:prisma@db:5432/mydatabase?schema=public"
    volumes:
      - .:/app
    ports:
      - "3000:3000"

volumes:
  db_data:
  esdata: 
    driver: local

networks:
  esnet:
    driver: bridge 